// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DeleteModalController from "./delete_modal_controller"
application.register("delete-modal", DeleteModalController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HeadquartersController from "./headquarters_controller"
application.register("headquarters", HeadquartersController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RadioSelectionController from "./radio_selection_controller"
application.register("radio-selection", RadioSelectionController)
